### PR TITLE
Added some improvements, a new node, and introduced a multi-mask feature.

### PR DESCRIPTION
**Pull request by dnl13**
I am not 100% shure if this DeviceSelector will work on e.g MacOS or any Device without "cuda:0" 
but maybe we can test it.
 
This is a posible Layout of the Nodes. 
only_screenshot

Checkout that i have removed the "mask to image" because there are so many other custom nodes that already have this feature. 
Every double/redudant node in Comfy is one node to much imho.

### CODE REVIEW

**Comment by dnl13** [comment]
Regarding this https://github.com/storyicon/comfyui_segment_anything/issues/4 conversation conversation, I'm going to make some changes to the code again. Please do not merge until I have been able to add the automatic device selection. Thank you!

**Comment by dnl13** [comment]
Added device selector in GroundingDinoSAMSegment-Node for those who want to run all the processes on a specific device. 

When you select 'Auto,' which is the default, `comfy.model_management.get_torch_device()` will be utilized. Otherwise, the model will first be loaded to the `default comfy.model_management.get_torch_device()`, and if you switch the device in the GroundingDinoSAMSegment-Node, it will be moved to the selected device.

Imho after testing, this PR is ready to merge.

**Comment by dnl13** [comment]
#### Prompt Optimization Features:
Added some prompt optimization features, similar to https://github.com/storyicon/comfyui_segment_anything/pull/16. Additionally, when you enable 'optimize_prompt_for_dino,' any occurrences of ',' will be replaced by '.' This enhancement leads to significantly better results. Habits are habits.

#### Added missing requirements:
Included missing dependencies in requirements.txt.

#### Nothing detected:
When DINO is unable to detect something, it will provide the original image along with an empty mask. Additionally, a message is displayed in the command prompt.

#### Moved functions:
Functions have been relocated to node_functions.py for improved readability.

#### Note:
The only scenario where you might encounter error messages is if the box_threshold is set too low, leading to memory exhaustion.

**Comment by dnl13** [comment]
In my opinion, most of the necessary fixes have already been implemented.

https://github.com/storyicon/comfyui_segment_anything/issues/13
https://github.com/storyicon/comfyui_segment_anything/issues/4
https://github.com/storyicon/comfyui_segment_anything/issues/10
https://github.com/storyicon/comfyui_segment_anything/issues/12
https://github.com/storyicon/comfyui_segment_anything/issues/6

Now, it's mainly about extending features. If you don't mind, @storyicon, it seems there is a demand for a merge.

**Comment by alessandroperilli** [comment]
I just published [AP Workflow 6.0](https://perilli.com/ai/comfyui/), featuring this custom node suite in a function called _Object Swapper_. 

@storyicon: the merge of @dnl13's PR would be extremely helpful for those people who want to use the workflow on Apple Silicon. Thank you!

**Comment by dnl13** [comment]
Okay, for now, I'll close this pull request. As we discussed here https://github.com/storyicon/comfyui_segment_anything/issues/19, I've set up my own repository for segmentation. If there's still interest in this pull request, please let me know.


I will archive my fork of this repository, in case anyone wants to check how and where I made fixes to help repair your local installations.

For those interested in the new repository, you can follow this link: https://github.com/dnl13/ComfyUI-dnl13-seg

**Pull request closed without merging**
