### PR TITLE
Added support for pipe-separated captions so you can detect many things at once

### PR DESCRIPTION
**Pull request by ttulttul**
Prior to this PR, detecting more than one thing required setting up more than one SAM segment node, since the SAM detector model does not reliably detect multiple concepts described by a single prompt. With this PR, you can now enter a list of prompts (captions) you wish to detect. For example, the prompt "car | bus | bicycle" will pass the three separate captions "car," "bus," and "bicycle" to the SAM detector model. The bounding boxes for the detected things are concatenated along the 0-dimension and everything else works in precisely the same way as before.

### CODE REVIEW

**Comment by ttulttul** [comment]
... And I just saw this: https://github.com/IDEA-Research/Grounded-Segment-Anything#running_man-groundingdino-detect-everything-with-text-prompt:~:text=If%20you%20want%20to%20detect%20multiple%20objects%20in%20one%20sentence%20with%20Grounding%20DINO%2C%20we%20suggest%20separating%20each%20name%20with%20.%20.%20An%20example%3A%20cat%20.%20dog%20.%20chair%20.

So apparently you can just separate the objects you want to detect with a period and the model will do the right thing. Feel free to ignore this PR.

**Comment by dnl13** [comment]
you can also use , instead of . 
but maybe we can try do it better to get this all over prompting feeling back in again ?

**Comment by ttulttul** [comment]
> you can also use , instead of . but maybe we can try do it better to get this all over prompting feeling back in again ?

The Grounding Dino library is a bit non-standard in using the period character to separate prompts. Overall this is an area in which ComfyUI needs a bit more standardization. There are many different ways to provide text input in various nodes and it is easy for beginners to get confused to say the least. I wish I had a solution to suggest.

**Comment by ttulttul** [comment]
Hi Daniel,

Okay - will do!

**Pull request closed without merging**
